# Generated by Django 3.2.10 on 2021-12-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_snippet_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commented_by',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='タグ名')),
                ('snippets', models.ManyToManyField(related_name='tags', related_query_name='tag', to='snippets.Snippet')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
